#! /bin/sh

source "$HOME/.secret"

xrandr --output HDMI-0 --mode 1920x1080 --rate 60 --pos 0x0
xrandr --output DP-2 --mode 1920x1080 --rate 144 --pos 1920x0

pgrep -x sxhkd > /dev/null || sxhkd &

picom -f --experimental-backends &

~/.config/polybar/launch.sh

bspc monitor HDMI-0 -d 1 2 3
bspc monitor DP-2 -d 4 5 6 7 8 9 0

bspc config border_width         0
bspc config window_gap           15

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

bspc rule -a Gimp state=floating follow=on
bspc rule -a Steam state=floating
bspc rule -a Discord state=floating

feh --bg-fill $HOME/wallpaper.jpg &

bspc config bottom_padding 0
bspc config top_padding 30
bspc config left_padding 0
bspc config right_padding 0

xsetroot -cursor_name left_ptr
xinput --set-prop 13 'libinput Accel Speed' -0.75

bspc wm --reorder-monitors DP-2 HDMI-0
